#!/bin/bash

system_type=$(uname -s)

if [ "$system_type" = "Linux"]; then
    if [! command -v nvim >/dev/null 2>&1]; then
        echo "Installing neovim"
    fi

    if [ ! -f "$HOME/.TinyTeX"]; then
        echo "Installing TinyTeX"
        wget -qO- "https://yihui.org/tinytex/install-bin-unix.sh" | sh
    fi

    export PATH=$PATH:/root/bin
fi
