#!/bin/bash

system_type=$(uname -s)

if [ "$system_type" = "Linux" ]; then
    if ! command -v nvim &> /dev/null
    then
        echo "Installing neovim"
	sudo apt-get install ninja-build gettext libtool libtool-bin autoconf automake cmake g++ pkg-config unzip curl
	cd $HOME
	git clone https://github.com/neovim/neovim
	cd neovim && make CMAKE_BUILD_TYPE=Release
	sudo make install
    fi

    if [ ! -d "$HOME/.TinyTeX" ]; then
        echo "Installing TinyTeX"
        wget -qO- "https://yihui.org/tinytex/install-bin-unix.sh" | sh
        export PATH=$PATH:/root/bin
    fi

    if [ ! -d "$HOME/Dropbox" ]; then
        echo "Installing Dropbox"
        cd ~ && wget -O - "https://www.dropbox.com/download?plat=lnx.x86_64" | tar xzf - && ~/.dropbox-dist/dropboxd
    fi
fi
